// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const boardExists = `-- name: BoardExists :one
SELECT EXISTS (SELECT 1 FROM boards WHERE id = $1::uuid) AS exists
`

func (q *Queries) BoardExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, boardExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (name, position)
SELECT $1::text, COALESCE(MAX(position), -1) + 1
FROM boards
RETURNING id, name, position, created_at, updated_at
`

func (q *Queries) CreateBoard(ctx context.Context, name string) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard, name)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCard = `-- name: CreateCard :one
INSERT INTO cards (column_id, title, description, assignee, priority, due_date, position)
SELECT $1::uuid,
       $2::text,
       COALESCE($3::text, ''),
       COALESCE($4::text, ''),
       $5::text,
       $6::date,
       COALESCE(MAX(position), -1) + 1
FROM cards
WHERE column_id = $1::uuid
RETURNING id, column_id, title, description, assignee, priority, due_date, position, created_at, updated_at
`

type CreateCardParams struct {
	ColumnID    uuid.UUID   `json:"column_id"`
	Title       string      `json:"title"`
	Description *string     `json:"description"`
	Assignee    *string     `json:"assignee"`
	Priority    string      `json:"priority"`
	DueDate     pgtype.Date `json:"due_date"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.ColumnID,
		arg.Title,
		arg.Description,
		arg.Assignee,
		arg.Priority,
		arg.DueDate,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Assignee,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createColumn = `-- name: CreateColumn :one
INSERT INTO board_columns (board_id, name, position)
SELECT $1::uuid,
       $2::text,
       COALESCE(MAX(position), -1) + 1
FROM board_columns
WHERE board_id = $1::uuid
RETURNING id, board_id, name, position, created_at, updated_at
`

type CreateColumnParams struct {
	BoardID uuid.UUID `json:"board_id"`
	Name    string    `json:"name"`
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, createColumn, arg.BoardID, arg.Name)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :execrows
DELETE FROM boards
WHERE id = $1::uuid
`

func (q *Queries) DeleteBoard(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBoard, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCard = `-- name: DeleteCard :execrows
DELETE FROM cards
WHERE id = $1::uuid
`

func (q *Queries) DeleteCard(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCard, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteColumn = `-- name: DeleteColumn :execrows
DELETE FROM board_columns
WHERE id = $1::uuid
`

func (q *Queries) DeleteColumn(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteColumn, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBoard = `-- name: GetBoard :one
SELECT id, name, position, created_at, updated_at
FROM boards
WHERE id = $1::uuid
`

func (q *Queries) GetBoard(ctx context.Context, id uuid.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCard = `-- name: GetCard :one
SELECT id, column_id, title, description, assignee, priority, due_date, position, created_at, updated_at
FROM cards
WHERE id = $1::uuid
`

func (q *Queries) GetCard(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, getCard, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Assignee,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getColumn = `-- name: GetColumn :one
SELECT id, board_id, name, position, created_at, updated_at
FROM board_columns
WHERE id = $1::uuid
`

func (q *Queries) GetColumn(ctx context.Context, id uuid.UUID) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, getColumn, id)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBoards = `-- name: ListBoards :many
SELECT id, name, position, created_at, updated_at
FROM boards
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListBoards(ctx context.Context) ([]Board, error) {
	rows, err := q.db.Query(ctx, listBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardIDsInColumn = `-- name: ListCardIDsInColumn :many
SELECT id
FROM cards
WHERE column_id = $1::uuid
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListCardIDsInColumn(ctx context.Context, columnID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCardIDsInColumn, columnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsForBoard = `-- name: ListCardsForBoard :many
SELECT c.id, c.column_id, c.title, c.description, c.assignee, c.priority, c.due_date, c.position, c.created_at, c.updated_at
FROM cards c
         JOIN board_columns col ON col.id = c.column_id
WHERE col.board_id = $1::uuid
ORDER BY col.position ASC, c.position ASC, c.created_at ASC
`

func (q *Queries) ListCardsForBoard(ctx context.Context, boardID uuid.UUID) ([]Card, error) {
	rows, err := q.db.Query(ctx, listCardsForBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.ColumnID,
			&i.Title,
			&i.Description,
			&i.Assignee,
			&i.Priority,
			&i.DueDate,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listColumnIDs = `-- name: ListColumnIDs :many
SELECT id
FROM board_columns
WHERE board_id = $1::uuid
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListColumnIDs(ctx context.Context, boardID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listColumnIDs, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listColumns = `-- name: ListColumns :many
SELECT id, board_id, name, position, created_at, updated_at
FROM board_columns
WHERE board_id = $1::uuid
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListColumns(ctx context.Context, boardID uuid.UUID) ([]BoardColumn, error) {
	rows, err := q.db.Query(ctx, listColumns, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardColumn
	for rows.Next() {
		var i BoardColumn
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCardColumn = `-- name: SetCardColumn :exec
UPDATE cards
SET column_id  = $1::uuid,
    updated_at = now()
WHERE id = $2::uuid
`

type SetCardColumnParams struct {
	ColumnID uuid.UUID `json:"column_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) SetCardColumn(ctx context.Context, arg SetCardColumnParams) error {
	_, err := q.db.Exec(ctx, setCardColumn, arg.ColumnID, arg.ID)
	return err
}

const setCardPosition = `-- name: SetCardPosition :exec
UPDATE cards
SET position   = $1::int,
    updated_at = now()
WHERE id = $2::uuid
`

type SetCardPositionParams struct {
	Position int32     `json:"position"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) SetCardPosition(ctx context.Context, arg SetCardPositionParams) error {
	_, err := q.db.Exec(ctx, setCardPosition, arg.Position, arg.ID)
	return err
}

const setColumnOrdinal = `-- name: SetColumnOrdinal :exec
UPDATE board_columns
SET position   = $1::int,
    updated_at = now()
WHERE id = $2::uuid
`

type SetColumnOrdinalParams struct {
	Position int32     `json:"position"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) SetColumnOrdinal(ctx context.Context, arg SetColumnOrdinalParams) error {
	_, err := q.db.Exec(ctx, setColumnOrdinal, arg.Position, arg.ID)
	return err
}

const updateBoardName = `-- name: UpdateBoardName :one
UPDATE boards
SET name       = $1::text,
    updated_at = now()
WHERE id = $2::uuid
RETURNING id, name, position, created_at, updated_at
`

type UpdateBoardNameParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateBoardName(ctx context.Context, arg UpdateBoardNameParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateBoardName, arg.Name, arg.ID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards
SET title       = $1::text,
    description = COALESCE($2::text, ''),
    assignee    = COALESCE($3::text, ''),
    priority    = $4::text,
    due_date    = $5::date,
    updated_at  = now()
WHERE id = $6::uuid
RETURNING id, column_id, title, description, assignee, priority, due_date, position, created_at, updated_at
`

type UpdateCardParams struct {
	Title       string      `json:"title"`
	Description *string     `json:"description"`
	Assignee    *string     `json:"assignee"`
	Priority    string      `json:"priority"`
	DueDate     pgtype.Date `json:"due_date"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.Title,
		arg.Description,
		arg.Assignee,
		arg.Priority,
		arg.DueDate,
		arg.ID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Assignee,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateColumnName = `-- name: UpdateColumnName :one
UPDATE board_columns
SET name       = $1::text,
    updated_at = now()
WHERE id = $2::uuid
RETURNING id, board_id, name, position, created_at, updated_at
`

type UpdateColumnNameParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateColumnName(ctx context.Context, arg UpdateColumnNameParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, updateColumnName, arg.Name, arg.ID)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
